version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '50000:80'
    volumes:
      - ./src/:/app
    depends_on:
      - app
  
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - '50001:3306'
    environment:
      MYSQL_DATABASE: genshin_pfp_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume: