version: "3.9"

volumes: 
  mysql-store:
  
services:
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: ./docker/client/Dockerfile
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./client:/app:cached
  #   command: yarn dev
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - nginx

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api/:/app
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./api/:/app
    depends_on:
      - api
  
  # db:
  #   build:
  #     context: .
  #     dockerfile: ./docker/db/Dockerfile
  #   ports:
  #     - 3306:3306
  #   enviroment:
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: password
  #     TZ: 'Asia/Tokyo'
  #   volumes:
  #     - mysql-volume:/var/lib/mysql